// Code generated by protoc-gen-go-adapter. DO NOT EDIT.

package proto

import (
	consulapi "github.com/hashicorp/consul/api"
	"github.com/mirrorsge/grpc-lb/registry/consul"
	"github.com/mirrorsge/grpc-lb/balancer"
	"google.golang.org/grpc"
	"context"
	"google.golang.org/grpc/grpclog"
)

var AlphaAdapter *AlphaService

func init() {
	consul.RegisterResolver("consul", &consulapi.Config{Address: "http://consul.aphrolime.top"}, "alpha:1.0")
	conn, err := grpc.Dial("consul:///", grpc.WithInsecure(), grpc.WithBalancerName(balancer.RoundRobin))
	if err != nil {
		grpclog.Error("init adapter file error,err is ", err)
		return
	}
	client := NewAlphaClient(conn)
	AlphaAdapter = &AlphaService{
		c: client,
	}
}

type AlphaService struct {
	c AlphaClient
}

func (p *AlphaService) Hello(ctx context.Context, in *HelloReq) (out *HelloRes, err error) {
	return p.c.Hello(ctx, in)
}
