// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlphaClient is the client API for Alpha service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlphaClient interface {
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error)
}

type alphaClient struct {
	cc grpc.ClientConnInterface
}

func NewAlphaClient(cc grpc.ClientConnInterface) AlphaClient {
	return &alphaClient{cc}
}

func (c *alphaClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error) {
	out := new(HelloRes)
	err := c.cc.Invoke(ctx, "/proto.Alpha/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlphaServer is the server API for Alpha service.
// All implementations must embed UnimplementedAlphaServer
// for forward compatibility
type AlphaServer interface {
	Hello(context.Context, *HelloReq) (*HelloRes, error)
	mustEmbedUnimplementedAlphaServer()
}

// UnimplementedAlphaServer must be embedded to have forward compatible implementations.
type UnimplementedAlphaServer struct {
}

func (UnimplementedAlphaServer) Hello(context.Context, *HelloReq) (*HelloRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedAlphaServer) mustEmbedUnimplementedAlphaServer() {}

// UnsafeAlphaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlphaServer will
// result in compilation errors.
type UnsafeAlphaServer interface {
	mustEmbedUnimplementedAlphaServer()
}

func RegisterAlphaServer(s grpc.ServiceRegistrar, srv AlphaServer) {
	s.RegisterService(&Alpha_ServiceDesc, srv)
}

func _Alpha_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlphaServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Alpha/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlphaServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Alpha_ServiceDesc is the grpc.ServiceDesc for Alpha service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Alpha_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Alpha",
	HandlerType: (*AlphaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Alpha_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alpha.proto",
}
